
# application
GIN_MODE=debug
SERVER_PORT=8000
BIND_IP=127.0.0.1
DOMAIN=localhost

# postgres
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=todo_system
POSTGRES_USER=todo_user
POSTGRES_PASSWORD=todo_pass

# pgadmin
PGADMIN_LISTEN_PORT=5050
PGADMIN_DEFAULT_EMAIL=admin@admin.ru
PGADMIN_DEFAULT_PASSWORD=123456

# redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_SECRET=lkjhLKJHOUGGHUfkh
REDIS_SIZE=10

# session
SESSION_NAME=todosystemsessiondebug

# JWT tokens
JWT_ACCESS_KEY=lshgowuhvjshhw
JWT_REFRESH_KEY=glkhwgo8iwhoig
ACCESS_TOKEN_EXPIRED_IN=2
REFRESH_TOKEN_EXPIRED_IN=4
ACCESS_TOKEN_MAXAGE=2
REFRESH_TOKEN_MAXAGE=4

# ACCESS_TOKEN_EXPIRED_IN=3600
# REFRESH_TOKEN_EXPIRED_IN=604800
# ACCESS_TOKEN_MAXAGE=3600
# REFRESH_TOKEN_MAXAGE=604800