
# application
GIN_MODE=debug
SERVER_PORT=8000
BIND_IP=127.0.0.1
PASSWORD_HASH_SALT=jk98hjh:JH88kjhikhU

# postgres
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=todo_system
POSTGRES_USER=todo_user
POSTGRES_PASSWORD=todo_pass

# pgadmin
PGADMIN_LISTEN_PORT=5050
PGADMIN_DEFAULT_EMAIL=admin@admin.ru
PGADMIN_DEFAULT_PASSWORD=123456

# redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_SECRET=lkjhLKJHOUGGHUfkh
REDIS_SIZE=10

# session
SESSION_NAME=todosystemsessiondebug

# JWT tokens
ACCESS_TOKEN_PRIVATE_KEY=lHuih98oIGUIF7PFTG*G(*)okuigiugiug
ACCESS_TOKEN_PUBLIC_KEY=LJKHG(*tpoIJHGu8guioGJ)ddd
REFRESH_TOKEN_PRIVATE_KEY=UF*&6r*(OGOLIHOUIGIYUG)dljgiouygfiug
REFRESH_TOKEN_PUBLIC_KEY=HKJFGHKK7jkghkjgughjghjhd
ACCESS_TOKEN_EXPIRED_IN=120
REFRESH_TOKEN_EXPIRED_IN=300
ACCESS_TOKEN_MAXAGE=120
REFRESH_TOKEN_MAXAGE=300
# ACCESS_TOKEN_EXPIRED_IN=3600
# REFRESH_TOKEN_EXPIRED_IN=604800
# ACCESS_TOKEN_MAXAGE=3600
# REFRESH_TOKEN_MAXAGE=604800