GIN_MODE=debug
SERVER_PORT=8000
BIND_IP=127.0.0.1

PASSWORD_HASH_SALT=jk98hjh:JH88kjhikhU

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=todo_system
POSTGRES_USER=todo_user
POSTGRES_PASSWORD=todo_pass

PGADMIN_LISTEN_PORT=5050
PGADMIN_DEFAULT_EMAIL=admin@admin.ru
PGADMIN_DEFAULT_PASSWORD=123456

REDIS_HOST=redis
REDIS_PORT=6379
